/* ==========================================================
   P31 PARTNERSHIP INQUIRIES INITIALIZATION
   ========================================================== */

-- 1. Create table for storing partnership inquiries
CREATE TABLE IF NOT EXISTS partnerships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  partnership_type TEXT NOT NULL, -- e.g. Financial, In-Kind, Strategic, Volunteer
  message TEXT,
  status TEXT DEFAULT 'unread', -- unread, contacted, archived
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Realtime for this table so Admins see new inquiries instantly
ALTER TABLE partnerships REPLICA IDENTITY FULL;

-- 3. Add to realtime publication if exists
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE partnerships;
  END IF;
END $$;

-- 4. Set RLS Policies
ALTER TABLE partnerships ENABLE ROW LEVEL SECURITY;

-- Allow anyone to submit an inquiry
CREATE POLICY "Enable insert for everyone" ON partnerships 
FOR INSERT TO public 
WITH CHECK (true);

-- Allow only authenticated Admins to view inquiries
CREATE POLICY "Admins can view inquiries" ON partnerships 
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() 
    AND email IN ('info@lumenlabsatl.com', 'proverbs31markets@gmail.com')
  )
);

-- Allow only Admins to delete/update status
CREATE POLICY "Admins can update inquiries" ON partnerships 
FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() 
    AND email IN ('info@lumenlabsatl.com', 'proverbs31markets@gmail.com')
  )
);
