/* ==========================================================
   P31 MARKETPLACE — MASTER SCHEMA
   ========================================================== */

-- 1. Profiles Table (Main User Identity)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Curator Details (Business Identity & Vanity URLs)
CREATE TABLE IF NOT EXISTS curator_data (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  business_name TEXT,
  tagline TEXT,
  bio TEXT,
  slug TEXT UNIQUE, 
  is_paid BOOLEAN DEFAULT FALSE,
  is_early_bird BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent curators from using reserved site paths as their URL
  CONSTRAINT slug_not_reserved CHECK (
    slug NOT IN ('about', 'directory', 'login', 'dashboard', 'visionary', 'apply', 'community', 'register', 'onboarding-exclusive')
  )
);

-- 3. Community Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  channel_id TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE curator_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 5. Security Policies
-- Anyone can view profiles/curators; only owners can edit them
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Curator data is public" ON curator_data FOR SELECT USING (true);
CREATE POLICY "Curators can update own data" ON curator_data FOR UPDATE USING (auth.uid() = id);

-- Chat: Only logged-in users can see and post
CREATE POLICY "Authenticated users can see chat" ON messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can post chat" ON messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = profile_id);
