/* ==========================================================
   P31 MARKETPLACE — V7 COMMUNICATIONS & TESTIMONIALS
   ========================================================== */

-- 1. Private Messaging System
CREATE TABLE IF NOT EXISTS private_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE private_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages" 
ON private_messages FOR SELECT 
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can send messages" 
ON private_messages FOR INSERT 
WITH CHECK (auth.uid() = sender_id);

-- 2. Customer Testimonials System
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curator_id UUID REFERENCES curator_data(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  content TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  is_approved BOOLEAN DEFAULT TRUE, -- Default true for now, can be moderated by admin
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Testimonials are viewable by everyone" 
ON testimonials FOR SELECT 
USING (is_approved = TRUE);

CREATE POLICY "Curators can manage their testimonials" 
ON testimonials FOR ALL 
USING (auth.uid() = curator_id);
