/* ==========================================================
   P31 MARKETPLACE — STOREFRONT & PRODUCT SCHEMA
   ========================================================== */

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curator_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Logic to help enforce the 10-product limit at the DB level eventually
  -- For now, we'll enforce it in the UI and with RLS if possible
  CONSTRAINT product_owner_check CHECK (curator_id IS NOT NULL)
);

-- 2. Expand Curator Data for Storefront Workflow
ALTER TABLE curator_data 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE;

-- 3. Security Policies for Products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone" 
ON products FOR SELECT 
USING (true);

CREATE POLICY "Curators can manage their own products" 
ON products FOR ALL 
USING (auth.uid() = curator_id);

-- 4. Storage Bucket for Products
-- To be run in Supabase SQL Editor:
/*
INSERT INTO storage.buckets (id, name, public) VALUES ('products', 'products', true);

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'products');
CREATE POLICY "Curator Upload Access" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'products' AND auth.role() = 'authenticated');
CREATE POLICY "Curator Update Access" ON storage.objects FOR UPDATE USING (bucket_id = 'products' AND auth.role() = 'authenticated');
CREATE POLICY "Curator Delete Access" ON storage.objects FOR DELETE USING (bucket_id = 'products' AND auth.role() = 'authenticated');
*/
