/* ==========================================================
   P31 MARKETPLACE — V5 GOVERNANCE & PRODUCT REFINEMENT
   ========================================================== */

-- 1. Add Featured Status to Curator Data
ALTER TABLE curator_data 
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;

-- 2. Add Stock Status to Products
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS stock_status TEXT DEFAULT 'in_stock'; -- 'in_stock', 'out_of_stock', 'limited_edition', 'pre_order'

-- 3. Add Click Tracking (Analytics) Table
CREATE TABLE IF NOT EXISTS curator_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curator_id UUID REFERENCES curator_data(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL, -- 'profile_view', 'product_click', 'payment_click'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS for Analytics
ALTER TABLE curator_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are viewable by owners" 
ON curator_analytics FOR SELECT 
USING (auth.uid() = curator_id);

CREATE POLICY "Public can insert analytics" 
ON curator_analytics FOR INSERT 
WITH CHECK (true);
